---
- name: Create vlan
  hosts: all
  gather_facts: false
  connection: network_cli

  tasks:
    - name: Create VLAN
      ios_vlan:
        vlan_id: "{{vlan}}" 
        name: test-vlan
        state: present
