---
- name: Backup devices configs
  hosts: all
  gather_facts: false
  connection: network_cli

  tasks:

    - name: Read IOS configs
      ios_command:
        commands: show run
      register: output

    - name: Save IOS config
      copy:
        content: "{{ output.stdout[0] }}"
        dest: "~/netor/netor/ansible/backup/show_run_{{ inventory_hostname }}.txt"
