---
- name: IOS and NxOS Copy running-config startup-config  
  hosts: all
  gather_facts: false
  connection: network_cli
  
  tasks:

    - name: IOS and NxOS Copy running-config startup-config
      ios_command:
        commands: copy running-config startup-config
      when: (ansible_network_os == 'ios') or (ansible_network_os == 'nxos')
      register: output

    - name: IOS NxOS save config
      debug:
        msg: "{{ output }}"
      when: (ansible_network_os == 'ios') or (ansible_network_os == 'nxos')
