---
- name: Slack Messaging
  hosts: localhost
  gather_facts: false
  tasks:
  
  - name: Send message to Slack
    slack:
      token: your_slack_token_goes_here
      msg: 'Test message from Ansible'
    delegate_to: localhost
