# usage example: ansible-playbook win-cmd.yml --extra-vars "cmd=ping source=ansible_hostname destination=ip/hostname'"
---
- name: Win Execute command playbook
  hosts: localhost
  gather_facts: false
  tasks:

    - name: Check connection to AD
      wait_for_connection:
        connect_timeout: 5
        timeout: 5
      register: connection
      ignore_errors: yes
      delegate_to: '{{ source }}'

    - name: Message to slack if connection failed
      local_action: command python3 scripts/connection-failed-msg-slack.py "{{ connection }}"

    - name: Win Execute command
      win_command: '{{ cmd }} {{destination}}'
      register: output
      delegate_to: '{{ source }}'

 #   - name: Send message to Slack
 #     slack:
 #       token: TQJ9F14QJ/BRMRLC4VA/ujbks1uJmrQomfhkHlzNwPOR
 #       msg: '{{ output.stdout }}'
 #     delegate_to: localhost

    - name: Send message to Slack using a python script
      local_action: command python3 scripts/win-ping-msg-slack.py "{{ output.stdout }}"
