# usage example: ansible-playbook win-user-expire-pass-local.yml --extra-vars "user=user_name server=server"
---
- name: Win expire user playbook Local
  hosts: '{{server}}'
  gather_facts: false
  tasks:

    - name: Check connection to Local
      wait_for_connection:
        connect_timeout: 3
        timeout: 5
      register: connection
      ignore_errors: yes

    - name: Win expire user Local
      win_user:
        name: '{{ user }}'
        password_expired: yes
        password: "L4.p4ss.D3fault"
      register: output

    - debug:
        msg: '{{ output }}'

