# usage example: ansible-playbook win-cmd.yml --extra-vars "cmd='ping win2019srv'"
---
- name: Win Execute command playbook
  hosts: win2019srv
  gather_facts: false
  tasks:

    - name: Win Execute command
      win_command: "{{ cmd }}"
      register: output
      ignore_errors: yes

    - debug:
        msg: '{{ output.stdout_lines }}'

    - name: Send message to Slack
      slack:
        token: TQJ9F14QJ/BRMD5MVDM/B5Ddv6bnsPl579gMaAWoF3wx
        msg: '{{ output.stdout }}'
      delegate_to: localhost


