# usage example: ansible-playbook win-user-disable-ad.yml --extra-vars "user=user_name"
---
- name: Win disable user playbook AD
  hosts: ad
  gather_facts: false
  tasks:

    - name: Check connection to AD
      wait_for_connection:
        connect_timeout: 3
        timeout: 5
      register: connection
      ignore_errors: yes

    - name: Win disable user AD
      win_domain_user:
        name: '{{ user }}'
        account_disabled: yes
      register: output

    - debug:
        msg: '{{ output }}'

