# usage example: ansible-playbook win-user-group-ad.yml --extra-vars "user=user_name group=group_name state=present/absent"
---
- name: Win user group playbook AD
  hosts: ad
  gather_facts: false
  tasks:

    - name: Check connection to AD
      wait_for_connection:
        connect_timeout: 3
        timeout: 5
      register: connection
      ignore_errors: yes

    - debug:
        msg: '{{connection}}'

    - name: Message to slack if connection failed
      local_action: command python3 scripts/connection-failed-msg-slack.py "{{ connection }}"

    - name: Win check user existance
      win_domain_user:
        name: "{{ user }}"
        state: query
      register: existance

    - debug:
        msg: '{{ existance }}'

    - name: Win user group task AD
      win_domain_group_membership:
        name: '{{ group }}'
        members:
          - '{{ user }}'
        state: '{{ state }}'
      when: existance.state == "present"
      register: output
      ignore_errors: yes

    - name: Send message to Slack using a python script
      local_action: command python3 scripts/win-user-group-msg-slack.py "{{ output }}" "{{ user }}" "{{ group }}"
