# usage example: ansible-playbook win-user-create-ad.yml --extra-vars "first_name=first_name, last_name=last_name, userid=userid"
---
- name: Win Create user playbook AD
  hosts: ad
  gather_facts: false
  tasks:

    - name: Check connection to AD
      wait_for_connection:
        connect_timeout: 3
        timeout: 5
      register: connection
      ignore_errors: yes

    - debug:
        msg: '{{ connection }}'

    - name: Win check user existance AD
      win_domain_user:
        name: "{{ userid }}"
        state: query
      register: existance

    - debug:
        msg: '{{ existance }}'

    - name: Win user create AD
      win_domain_user:
        name: '{{ userid }}'
        firstname: '{{ first_name }}'
        lastname: '{{ last_name }}'
        password: 'L4.p4ss.D3fault'
        state: present
      when: existance.state == "absent"
      register: output

    - debug:
        msg: '{{ output }}'
