# usage example: ansible-playbook win-os-cmd.yml --extra-vars "cmd=ping source=ansible_hostname destination=ip/hostname'"
---
- name: Win ping playbook
  hosts: localhost
  gather_facts: false
  tasks:

    - name: Check connection to AD
      wait_for_connection:
        connect_timeout: 5
        timeout: 5
      register: connection
      ignore_errors: yes
      delegate_to: '{{ source }}'

    - name: Win ping
      win_command: '{{ cmd }} {{destination}}'
      register: output
      delegate_to: '{{ source }}'

    - debug:
        msg: '{{ output.stdout_lines }}'
