---
- name: parser meta data
  parser_metadata:
    version: 1.0
    command: show version
    network_os: ios

- name: match hostname
  pattern_match:
    regex: "(.*) uptime is "
  register: hn
  #export: yes

- name: match Hardware version
  pattern_match:
    regex: "Cisco (.*) .* processor"
  register: hv
  #export: yes

- name: match Serial Number
  pattern_match:
    regex: "Processor board ID (.*)"
  register: sn
  #export: yes

- name: match Software Image
  pattern_match:
    regex: "Cisco IOS Software, .* \\((.*)\\), Version "
  register: si
  #export: yes

- name: match Software Version
  pattern_match:
    regex: "Cisco IOS Software, .*, Version (.*), RELEASE SOFTWARE"
  register: sv
  #export: yes

- name: match Software Release
  pattern_match:
    regex: "Cisco IOS Software, .*, RELEASE SOFTWARE \\((.*)\\)"
  register: sr
  #export: yes

- name: generate json data structure
  set_vars:
    Hardware_Version: "{{ hv.matches.0 }}"
    Serial_Number: "{{ sn.matches.0 }}"
    Software_Image: "{{ si.matches.0 }}"
    Software_Version: "{{ sv.matches.0 }}"
    Software_Release: "{{ sr.matches.0 }}"
  export: true
  #export_as: "{{ export_type }}"
  register: config

