# usage example: ansible-playbook win-user-create-local.yml --extra-vars "fullname=full_name, user=user, server=server"
---
- name: Win Create user playbook AD
  hosts: '{{ server }}'
  gather_facts: false
  tasks:

    - name: Check connection to Server
      wait_for_connection:
        connect_timeout: 3
        timeout: 5
      register: connection
      ignore_errors: yes

    - name: Win check user existance Server
      win_user:
        name: '{{ user }}'
        state: query
      register: existance

    - debug:
        msg: '{{ existance }}'

    - name: Win user create Server
      win_user:
        name: '{{ user }}'
        fullname: '{{ fullname }}'
        password: 'L4.p4ss.D3fault'
        state: present
      when: existance.state == "absent"
      register: output

    - debug:
        msg: '{{ output }}'
