# usage example: ansible-playbook win-user-unlock-local.yml --extra-vars "user=user_name"
---
- name: Win unlock user playbook AD
  hosts: ad
  gather_facts: false
  tasks:

    - name: Check connection to AD
      wait_for_connection:
        connect_timeout: 3
        timeout: 5
      register: connection
      ignore_errors: yes

    - name: Win unlock user AD
      win_domain_user:
        name: '{{ user }}'
        account_locked: no
      register: output

    - debug:
        msg: '{{ output }}'

