# usage example: ansible-playbook win-user-view-local-basic.yml --extra-vars "user=user_name server=server"
---
- name: Win view Full user playbook Local
  hosts: '{{ server }}'
  gather_facts: false
  tasks:

    - name: Check connection to Server
      wait_for_connection:
        connect_timeout: 3
        timeout: 5
      register: connection
      ignore_errors: yes

    - name: Win view user Local
      win_user:
        name: '{{ user }}'
        state: query
      register: output

    - debug:
        msg: '{{ output }}'

