# usage example: ansible-playbook win-os-cmd.yml --extra-vars "cmd=ping source=ansible_hostname destination=ip/hostname channel=channel_name"
---
- name: Win Execute command playbook
  hosts: localhost
  gather_facts: false
  tasks:

    - name: Check connection to AD
      wait_for_connection:
        connect_timeout: 5
        timeout: 5
      register: connection
      ignore_errors: yes
      delegate_to: '{{ source }}'

    - name: Message to slack if connection failed
      local_action: command python3 scripts/win-user-connection-failed-msg-slack.py "{{ connection }}" "{{ channel }}"

    - name: Win Execute command
      win_command: '{{ cmd }} {{destination}}'
      register: output
      delegate_to: '{{ source }}'

    - name: Send message to Slack using a python script
      local_action: command python3 scripts/win-os-ping-msg-slack.py "{{ output.stdout }}" "{{ channel }}"
