# usage example: ansible-playbook win-user-view-ad-basic.yml --extra-vars "user=user_name"
---
- name: Win view Basic user playbook AD
  hosts: ad
  gather_facts: false
  tasks:

    - name: Check connection to AD
      wait_for_connection:
        connect_timeout: 3
        timeout: 5
      register: connection
      ignore_errors: yes

    - name: Win view user AD
      win_domain_user:
        name: "{{ user }}"
        state: query
      register: output

    - debug:
        msg: '{{ output}}'
